<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="10.0.4" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="10.0.4" />
    <PackageReference Include="MediatR" Version="10.0.1" />
    <PackageReference Include="NuGet.Packaging" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AutoMapper">
      <HintPath>..\..\..\Company\Company\bin\Debug\net10.0\AutoMapper.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
